### ISSUE TITLE
`tail` may be popped twice?

### ISSUE THREAD

**Issue by hxzhao527** [grivet/mpsc-queue#2]
https://github.com/grivet/mpsc-queue/blob/48b54eb3f7cbc474fdee660fa5df98257e4f01c2/mpsc-queue.h#L75-L83

I'm not familiar with c++. But  I doubt that `mpsc_queue_push_front` maybe cause `tail` popped twice.

At the _line 80_ load `queue->tail`, then store back.  
the `queue->tail` may have been updated to other in `mpsc_queue_poll`, for example
https://github.com/grivet/mpsc-queue/blob/48b54eb3f7cbc474fdee660fa5df98257e4f01c2/mpsc-queue.h#L100

**Comment by grivet** [comment]
Hey,

Thanks for looking into the internals of this structure.

You are correct that if different threads are manipulating the tail, there is nothing preventing double-pop. There is no safe way for the N producers to re-insert nodes in the queue. For this reason, 'tail-manipulating' functions such as `mpsc_queue_push_front` is part of the consumer API as documented:

https://github.com/grivet/mpsc-queue/blob/48b54eb3f7cbc474fdee660fa5df98257e4f01c2/mpsc-queue.h#L33-L35

https://github.com/grivet/mpsc-queue/blob/48b54eb3f7cbc474fdee660fa5df98257e4f01c2/mpsc-queue.h#L65

Only the consumer is allowed to re-enqueue a node. In that context, there cannot be any race conditions or double-pop on that node, as long as only a single thread at a time is the consumer.

I had put thread-safety decorators before to enforce those requirements with proper compilers, but it pulled dependencies on lock implementations (posix) that I preferred to avoid. It would have made things much clearer, but I don't see a good way to do it portably and without pulling too many deps.

**Comment by hxzhao527** [comment]
Thanks.

I just get the meaning of `/* Consumer API. */` 😆
